# Base de données locale des grandes actions (EU & US)
# Format attendu par notre convertisseur : Google Finance (Bourse:Symbole)

MAJOR_STOCKS = {
    "--- Saisir manuellement ---": "CUSTOM",
    "3M (US)": "NASDAQ:MMM",
    "A. O. Smith (US)": "NASDAQ:AOS",
    "Abbott Laboratories (US)": "NASDAQ:ABT",
    "AbbVie (US)": "NASDAQ:ABBV",
    "Accenture (US)": "NASDAQ:ACN",
    "Adobe Inc. (US)": "NASDAQ:ADBE",
    "Advanced Micro Devices (US)": "NASDAQ:AMD",
    "AES Corporation (US)": "NASDAQ:AES",
    "Aflac (US)": "NASDAQ:AFL",
    "Agilent Technologies (US)": "NASDAQ:A",
    "Air Products (US)": "NASDAQ:APD",
    "Airbnb (US)": "NASDAQ:ABNB",
    "Akamai Technologies (US)": "NASDAQ:AKAM",
    "Albemarle Corporation (US)": "NASDAQ:ALB",
    "Alexandria Real Estate Equities (US)": "NASDAQ:ARE",
    "Align Technology (US)": "NASDAQ:ALGN",
    "Allegion (US)": "NASDAQ:ALLE",
    "Alliant Energy (US)": "NASDAQ:LNT",
    "Allstate (US)": "NASDAQ:ALL",
    "Alphabet Inc. (Class A) (US)": "NASDAQ:GOOGL",
    "Alphabet Inc. (Class C) (US)": "NASDAQ:GOOG",
    "Altria (US)": "NASDAQ:MO",
    "Amazon (US)": "NASDAQ:AMZN",
    "Amcor (US)": "NASDAQ:AMCR",
    "Ameren (US)": "NASDAQ:AEE",
    "American Electric Power (US)": "NASDAQ:AEP",
    "American Express (US)": "NASDAQ:AXP",
    "American International Group (US)": "NASDAQ:AIG",
    "American Tower (US)": "NASDAQ:AMT",
    "American Water Works (US)": "NASDAQ:AWK",
    "Ameriprise Financial (US)": "NASDAQ:AMP",
    "Ametek (US)": "NASDAQ:AME",
    "Amgen (US)": "NASDAQ:AMGN",
    "Amphenol (US)": "NASDAQ:APH",
    "Analog Devices (US)": "NASDAQ:ADI",
    "Aon plc (US)": "NASDAQ:AON",
    "APA Corporation (US)": "NASDAQ:APA",
    "Apollo Global Management (US)": "NASDAQ:APO",
    "Apple Inc. (US)": "NASDAQ:AAPL",
    "Applied Materials (US)": "NASDAQ:AMAT",
    "AppLovin (US)": "NASDAQ:APP",
    "Aptiv (US)": "NASDAQ:APTV",
    "Arch Capital Group (US)": "NASDAQ:ACGL",
    "Archer Daniels Midland (US)": "NASDAQ:ADM",
    "Ares Management (US)": "NASDAQ:ARES",
    "Arista Networks (US)": "NASDAQ:ANET",
    "Arthur J. Gallagher & Co. (US)": "NASDAQ:AJG",
    "Assurant (US)": "NASDAQ:AIZ",
    "AT&T (US)": "NASDAQ:T",
    "Atmos Energy (US)": "NASDAQ:ATO",
    "Autodesk (US)": "NASDAQ:ADSK",
    "Automatic Data Processing (US)": "NASDAQ:ADP",
    "AutoZone (US)": "NASDAQ:AZO",
    "AvalonBay Communities (US)": "NASDAQ:AVB",
    "Avery Dennison (US)": "NASDAQ:AVY",
    "Axon Enterprise (US)": "NASDAQ:AXON",
    "Baker Hughes (US)": "NASDAQ:BKR",
    "Ball Corporation (US)": "NASDAQ:BALL",
    "Bank of America (US)": "NASDAQ:BAC",
    "Baxter International (US)": "NASDAQ:BAX",
    "Becton Dickinson (US)": "NASDAQ:BDX",
    "Berkshire Hathaway (US)": "NASDAQ:BRK-B",
    "Best Buy (US)": "NASDAQ:BBY",
    "Bio-Techne (US)": "NASDAQ:TECH",
    "Biogen (US)": "NASDAQ:BIIB",
    "BlackRock (US)": "NASDAQ:BLK",
    "Blackstone Inc. (US)": "NASDAQ:BX",
    "Block, Inc. (US)": "NASDAQ:XYZ",
    "BNY Mellon (US)": "NASDAQ:BK",
    "Boeing (US)": "NASDAQ:BA",
    "Booking Holdings (US)": "NASDAQ:BKNG",
    "Boston Scientific (US)": "NASDAQ:BSX",
    "Bristol Myers Squibb (US)": "NASDAQ:BMY",
    "Broadcom (US)": "NASDAQ:AVGO",
    "Broadridge Financial Solutions (US)": "NASDAQ:BR",
    "Brown & Brown (US)": "NASDAQ:BRO",
    "Brown–Forman (US)": "NASDAQ:BF-B",
    "Builders FirstSource (US)": "NASDAQ:BLDR",
    "Bunge Global (US)": "NASDAQ:BG",
    "BXP, Inc. (US)": "NASDAQ:BXP",
    "C.H. Robinson (US)": "NASDAQ:CHRW",
    "Cadence Design Systems (US)": "NASDAQ:CDNS",
    "Camden Property Trust (US)": "NASDAQ:CPT",
    "Campbell's Company (The) (US)": "NASDAQ:CPB",
    "Capital One (US)": "NASDAQ:COF",
    "Cardinal Health (US)": "NASDAQ:CAH",
    "Carnival (US)": "NASDAQ:CCL",
    "Carrier Global (US)": "NASDAQ:CARR",
    "Carvana (US)": "NASDAQ:CVNA",
    "Casey's (US)": "NASDAQ:CASY",
    "Caterpillar Inc. (US)": "NASDAQ:CAT",
    "Cboe Global Markets (US)": "NASDAQ:CBOE",
    "CBRE Group (US)": "NASDAQ:CBRE",
    "CDW Corporation (US)": "NASDAQ:CDW",
    "Cencora (US)": "NASDAQ:COR",
    "Centene Corporation (US)": "NASDAQ:CNC",
    "CenterPoint Energy (US)": "NASDAQ:CNP",
    "CF Industries (US)": "NASDAQ:CF",
    "Charles River Laboratories (US)": "NASDAQ:CRL",
    "Charles Schwab Corporation (US)": "NASDAQ:SCHW",
    "Charter Communications (US)": "NASDAQ:CHTR",
    "Chevron Corporation (US)": "NASDAQ:CVX",
    "Chipotle Mexican Grill (US)": "NASDAQ:CMG",
    "Chubb Limited (US)": "NASDAQ:CB",
    "Church & Dwight (US)": "NASDAQ:CHD",
    "Ciena (US)": "NASDAQ:CIEN",
    "Cigna (US)": "NASDAQ:CI",
    "Cincinnati Financial (US)": "NASDAQ:CINF",
    "Cintas (US)": "NASDAQ:CTAS",
    "Cisco (US)": "NASDAQ:CSCO",
    "Citigroup (US)": "NASDAQ:C",
    "Citizens Financial Group (US)": "NASDAQ:CFG",
    "Clorox (US)": "NASDAQ:CLX",
    "CME Group (US)": "NASDAQ:CME",
    "CMS Energy (US)": "NASDAQ:CMS",
    "Coca-Cola Company (The) (US)": "NASDAQ:KO",
    "Cognizant (US)": "NASDAQ:CTSH",
    "Coherent Corp. (US)": "NASDAQ:COHR",
    "Coinbase (US)": "NASDAQ:COIN",
    "Colgate-Palmolive (US)": "NASDAQ:CL",
    "Comcast (US)": "NASDAQ:CMCSA",
    "Comfort Systems USA (US)": "NASDAQ:FIX",
    "Conagra Brands (US)": "NASDAQ:CAG",
    "ConocoPhillips (US)": "NASDAQ:COP",
    "Consolidated Edison (US)": "NASDAQ:ED",
    "Constellation Brands (US)": "NASDAQ:STZ",
    "Constellation Energy (US)": "NASDAQ:CEG",
    "Cooper Companies (The) (US)": "NASDAQ:COO",
    "Copart (US)": "NASDAQ:CPRT",
    "Corning Inc. (US)": "NASDAQ:GLW",
    "Corpay (US)": "NASDAQ:CPAY",
    "Corteva (US)": "NASDAQ:CTVA",
    "CoStar Group (US)": "NASDAQ:CSGP",
    "Costco (US)": "NASDAQ:COST",
    "Coterra (US)": "NASDAQ:CTRA",
    "CRH plc (US)": "NASDAQ:CRH",
    "CrowdStrike (US)": "NASDAQ:CRWD",
    "Crown Castle (US)": "NASDAQ:CCI",
    "CSX Corporation (US)": "NASDAQ:CSX",
    "Cummins (US)": "NASDAQ:CMI",
    "CVS Health (US)": "NASDAQ:CVS",
    "Danaher Corporation (US)": "NASDAQ:DHR",
    "Darden Restaurants (US)": "NASDAQ:DRI",
    "Datadog (US)": "NASDAQ:DDOG",
    "DaVita (US)": "NASDAQ:DVA",
    "Deckers Brands (US)": "NASDAQ:DECK",
    "Deere & Company (US)": "NASDAQ:DE",
    "Dell Technologies (US)": "NASDAQ:DELL",
    "Delta Air Lines (US)": "NASDAQ:DAL",
    "Devon Energy (US)": "NASDAQ:DVN",
    "Dexcom (US)": "NASDAQ:DXCM",
    "Diamondback Energy (US)": "NASDAQ:FANG",
    "Digital Realty (US)": "NASDAQ:DLR",
    "Dollar General (US)": "NASDAQ:DG",
    "Dollar Tree (US)": "NASDAQ:DLTR",
    "Dominion Energy (US)": "NASDAQ:D",
    "Domino's (US)": "NASDAQ:DPZ",
    "DoorDash (US)": "NASDAQ:DASH",
    "Dover Corporation (US)": "NASDAQ:DOV",
    "Dow Inc. (US)": "NASDAQ:DOW",
    "D. R. Horton (US)": "NASDAQ:DHI",
    "DTE Energy (US)": "NASDAQ:DTE",
    "Duke Energy (US)": "NASDAQ:DUK",
    "DuPont (US)": "NASDAQ:DD",
    "Eaton Corporation (US)": "NASDAQ:ETN",
    "eBay Inc. (US)": "NASDAQ:EBAY",
    "EchoStar (US)": "NASDAQ:SATS",
    "Ecolab (US)": "NASDAQ:ECL",
    "Edison International (US)": "NASDAQ:EIX",
    "Edwards Lifesciences (US)": "NASDAQ:EW",
    "Electronic Arts (US)": "NASDAQ:EA",
    "Elevance Health (US)": "NASDAQ:ELV",
    "Emcor (US)": "NASDAQ:EME",
    "Emerson Electric (US)": "NASDAQ:EMR",
    "Entergy (US)": "NASDAQ:ETR",
    "EOG Resources (US)": "NASDAQ:EOG",
    "EPAM Systems (US)": "NASDAQ:EPAM",
    "EQT Corporation (US)": "NASDAQ:EQT",
    "Equifax (US)": "NASDAQ:EFX",
    "Equinix (US)": "NASDAQ:EQIX",
    "Equity Residential (US)": "NASDAQ:EQR",
    "Erie Indemnity (US)": "NASDAQ:ERIE",
    "Essex Property Trust (US)": "NASDAQ:ESS",
    "Estée Lauder Companies (The) (US)": "NASDAQ:EL",
    "Everest Group (US)": "NASDAQ:EG",
    "Evergy (US)": "NASDAQ:EVRG",
    "Eversource Energy (US)": "NASDAQ:ES",
    "Exelon (US)": "NASDAQ:EXC",
    "Expand Energy (US)": "NASDAQ:EXE",
    "Expedia Group (US)": "NASDAQ:EXPE",
    "Expeditors International (US)": "NASDAQ:EXPD",
    "Extra Space Storage (US)": "NASDAQ:EXR",
    "ExxonMobil (US)": "NASDAQ:XOM",
    "F5, Inc. (US)": "NASDAQ:FFIV",
    "FactSet (US)": "NASDAQ:FDS",
    "Fair Isaac (US)": "NASDAQ:FICO",
    "Fastenal (US)": "NASDAQ:FAST",
    "Federal Realty Investment Trust (US)": "NASDAQ:FRT",
    "FedEx (US)": "NASDAQ:FDX",
    "Fidelity National Information Services (US)": "NASDAQ:FIS",
    "Fifth Third Bancorp (US)": "NASDAQ:FITB",
    "First Solar (US)": "NASDAQ:FSLR",
    "FirstEnergy (US)": "NASDAQ:FE",
    "Fiserv (US)": "NASDAQ:FISV",
    "Ford Motor Company (US)": "NASDAQ:F",
    "Fortinet (US)": "NASDAQ:FTNT",
    "Fortive (US)": "NASDAQ:FTV",
    "Fox Corporation (Class A) (US)": "NASDAQ:FOXA",
    "Fox Corporation (Class B) (US)": "NASDAQ:FOX",
    "Franklin Resources (US)": "NASDAQ:BEN",
    "Freeport-McMoRan (US)": "NASDAQ:FCX",
    "Garmin (US)": "NASDAQ:GRMN",
    "Gartner (US)": "NASDAQ:IT",
    "GE Aerospace (US)": "NASDAQ:GE",
    "GE HealthCare (US)": "NASDAQ:GEHC",
    "GE Vernova (US)": "NASDAQ:GEV",
    "Gen Digital (US)": "NASDAQ:GEN",
    "Generac (US)": "NASDAQ:GNRC",
    "General Dynamics (US)": "NASDAQ:GD",
    "General Mills (US)": "NASDAQ:GIS",
    "General Motors (US)": "NASDAQ:GM",
    "Genuine Parts Company (US)": "NASDAQ:GPC",
    "Gilead Sciences (US)": "NASDAQ:GILD",
    "Global Payments (US)": "NASDAQ:GPN",
    "Globe Life (US)": "NASDAQ:GL",
    "GoDaddy (US)": "NASDAQ:GDDY",
    "Goldman Sachs (US)": "NASDAQ:GS",
    "Halliburton (US)": "NASDAQ:HAL",
    "Hartford (The) (US)": "NASDAQ:HIG",
    "Hasbro (US)": "NASDAQ:HAS",
    "HCA Healthcare (US)": "NASDAQ:HCA",
    "Healthpeak Properties (US)": "NASDAQ:DOC",
    "Henry Schein (US)": "NASDAQ:HSIC",
    "Hershey Company (The) (US)": "NASDAQ:HSY",
    "Hewlett Packard Enterprise (US)": "NASDAQ:HPE",
    "Hilton Worldwide (US)": "NASDAQ:HLT",
    "Home Depot (The) (US)": "NASDAQ:HD",
    "Honeywell (US)": "NASDAQ:HON",
    "Hormel Foods (US)": "NASDAQ:HRL",
    "Host Hotels & Resorts (US)": "NASDAQ:HST",
    "Howmet Aerospace (US)": "NASDAQ:HWM",
    "HP Inc. (US)": "NASDAQ:HPQ",
    "Hubbell Incorporated (US)": "NASDAQ:HUBB",
    "Humana (US)": "NASDAQ:HUM",
    "Huntington Bancshares (US)": "NASDAQ:HBAN",
    "Huntington Ingalls Industries (US)": "NASDAQ:HII",
    "IBM (US)": "NASDAQ:IBM",
    "IDEX Corporation (US)": "NASDAQ:IEX",
    "Idexx Laboratories (US)": "NASDAQ:IDXX",
    "Illinois Tool Works (US)": "NASDAQ:ITW",
    "Incyte (US)": "NASDAQ:INCY",
    "Ingersoll Rand (US)": "NASDAQ:IR",
    "Insulet Corporation (US)": "NASDAQ:PODD",
    "Intel (US)": "NASDAQ:INTC",
    "Interactive Brokers (US)": "NASDAQ:IBKR",
    "Intercontinental Exchange (US)": "NASDAQ:ICE",
    "International Flavors & Fragrances (US)": "NASDAQ:IFF",
    "International Paper (US)": "NASDAQ:IP",
    "Intuit (US)": "NASDAQ:INTU",
    "Intuitive Surgical (US)": "NASDAQ:ISRG",
    "Invesco (US)": "NASDAQ:IVZ",
    "Invitation Homes (US)": "NASDAQ:INVH",
    "IQVIA (US)": "NASDAQ:IQV",
    "Iron Mountain (US)": "NASDAQ:IRM",
    "J.B. Hunt (US)": "NASDAQ:JBHT",
    "Jabil (US)": "NASDAQ:JBL",
    "Jack Henry & Associates (US)": "NASDAQ:JKHY",
    "Jacobs Solutions (US)": "NASDAQ:J",
    "Johnson & Johnson (US)": "NASDAQ:JNJ",
    "Johnson Controls (US)": "NASDAQ:JCI",
    "JPMorgan Chase (US)": "NASDAQ:JPM",
    "Kenvue (US)": "NASDAQ:KVUE",
    "Keurig Dr Pepper (US)": "NASDAQ:KDP",
    "KeyCorp (US)": "NASDAQ:KEY",
    "Keysight Technologies (US)": "NASDAQ:KEYS",
    "Kimberly-Clark (US)": "NASDAQ:KMB",
    "Kimco Realty (US)": "NASDAQ:KIM",
    "Kinder Morgan (US)": "NASDAQ:KMI",
    "KKR & Co. (US)": "NASDAQ:KKR",
    "KLA Corporation (US)": "NASDAQ:KLAC",
    "Kraft Heinz (US)": "NASDAQ:KHC",
    "Kroger (US)": "NASDAQ:KR",
    "L3Harris (US)": "NASDAQ:LHX",
    "Labcorp (US)": "NASDAQ:LH",
    "Lam Research (US)": "NASDAQ:LRCX",
    "Las Vegas Sands (US)": "NASDAQ:LVS",
    "Leidos (US)": "NASDAQ:LDOS",
    "Lennar (US)": "NASDAQ:LEN",
    "Lennox International (US)": "NASDAQ:LII",
    "Lilly (Eli) (US)": "NASDAQ:LLY",
    "Linde plc (US)": "NASDAQ:LIN",
    "Live Nation Entertainment (US)": "NASDAQ:LYV",
    "Lockheed Martin (US)": "NASDAQ:LMT",
    "Loews Corporation (US)": "NASDAQ:L",
    "Lowe's (US)": "NASDAQ:LOW",
    "Lululemon Athletica (US)": "NASDAQ:LULU",
    "Lumentum (US)": "NASDAQ:LITE",
    "LyondellBasell (US)": "NASDAQ:LYB",
    "M&T Bank (US)": "NASDAQ:MTB",
    "Marathon Petroleum (US)": "NASDAQ:MPC",
    "Marriott International (US)": "NASDAQ:MAR",
    "Marsh McLennan (US)": "NASDAQ:MRSH",
    "Martin Marietta Materials (US)": "NASDAQ:MLM",
    "Masco (US)": "NASDAQ:MAS",
    "Mastercard (US)": "NASDAQ:MA",
    "McCormick & Company (US)": "NASDAQ:MKC",
    "McDonald's (US)": "NASDAQ:MCD",
    "McKesson Corporation (US)": "NASDAQ:MCK",
    "Medtronic (US)": "NASDAQ:MDT",
    "Merck & Co. (US)": "NASDAQ:MRK",
    "Meta Platforms (US)": "NASDAQ:META",
    "MetLife (US)": "NASDAQ:MET",
    "Mettler Toledo (US)": "NASDAQ:MTD",
    "MGM Resorts (US)": "NASDAQ:MGM",
    "Microchip Technology (US)": "NASDAQ:MCHP",
    "Micron Technology (US)": "NASDAQ:MU",
    "Microsoft (US)": "NASDAQ:MSFT",
    "Mid-America Apartment Communities (US)": "NASDAQ:MAA",
    "Moderna (US)": "NASDAQ:MRNA",
    "Molson Coors Beverage Company (US)": "NASDAQ:TAP",
    "Mondelez International (US)": "NASDAQ:MDLZ",
    "Monolithic Power Systems (US)": "NASDAQ:MPWR",
    "Monster Beverage (US)": "NASDAQ:MNST",
    "Moody's Corporation (US)": "NASDAQ:MCO",
    "Morgan Stanley (US)": "NASDAQ:MS",
    "Mosaic Company (The) (US)": "NASDAQ:MOS",
    "Motorola Solutions (US)": "NASDAQ:MSI",
    "MSCI Inc. (US)": "NASDAQ:MSCI",
    "Nasdaq, Inc. (US)": "NASDAQ:NDAQ",
    "NetApp (US)": "NASDAQ:NTAP",
    "Netflix (US)": "NASDAQ:NFLX",
    "Newmont (US)": "NASDAQ:NEM",
    "News Corp (Class A) (US)": "NASDAQ:NWSA",
    "News Corp (Class B) (US)": "NASDAQ:NWS",
    "NextEra Energy (US)": "NASDAQ:NEE",
    "Nike, Inc. (US)": "NASDAQ:NKE",
    "NiSource (US)": "NASDAQ:NI",
    "Nordson Corporation (US)": "NASDAQ:NDSN",
    "Norfolk Southern (US)": "NASDAQ:NSC",
    "Northern Trust (US)": "NASDAQ:NTRS",
    "Northrop Grumman (US)": "NASDAQ:NOC",
    "Norwegian Cruise Line Holdings (US)": "NASDAQ:NCLH",
    "NRG Energy (US)": "NASDAQ:NRG",
    "Nucor (US)": "NASDAQ:NUE",
    "Nvidia (US)": "NASDAQ:NVDA",
    "NVR, Inc. (US)": "NASDAQ:NVR",
    "NXP Semiconductors (US)": "NASDAQ:NXPI",
    "O’Reilly Automotive (US)": "NASDAQ:ORLY",
    "Occidental Petroleum (US)": "NASDAQ:OXY",
    "Old Dominion (US)": "NASDAQ:ODFL",
    "Omnicom Group (US)": "NASDAQ:OMC",
    "ON Semiconductor (US)": "NASDAQ:ON",
    "Oneok (US)": "NASDAQ:OKE",
    "Oracle Corporation (US)": "NASDAQ:ORCL",
    "Otis Worldwide (US)": "NASDAQ:OTIS",
    "Paccar (US)": "NASDAQ:PCAR",
    "Packaging Corporation of America (US)": "NASDAQ:PKG",
    "Palantir Technologies (US)": "NASDAQ:PLTR",
    "Palo Alto Networks (US)": "NASDAQ:PANW",
    "Paramount Skydance Corporation (US)": "NASDAQ:PSKY",
    "Parker Hannifin (US)": "NASDAQ:PH",
    "Paychex (US)": "NASDAQ:PAYX",
    "PayPal (US)": "NASDAQ:PYPL",
    "Pentair (US)": "NASDAQ:PNR",
    "PepsiCo (US)": "NASDAQ:PEP",
    "Pfizer (US)": "NASDAQ:PFE",
    "PG&E Corporation (US)": "NASDAQ:PCG",
    "Philip Morris International (US)": "NASDAQ:PM",
    "Phillips 66 (US)": "NASDAQ:PSX",
    "Pinnacle West Capital (US)": "NASDAQ:PNW",
    "PNC Financial Services (US)": "NASDAQ:PNC",
    "Pool Corporation (US)": "NASDAQ:POOL",
    "PPG Industries (US)": "NASDAQ:PPG",
    "PPL Corporation (US)": "NASDAQ:PPL",
    "Principal Financial Group (US)": "NASDAQ:PFG",
    "Procter & Gamble (US)": "NASDAQ:PG",
    "Progressive Corporation (US)": "NASDAQ:PGR",
    "Prologis (US)": "NASDAQ:PLD",
    "Prudential Financial (US)": "NASDAQ:PRU",
    "Public Service Enterprise Group (US)": "NASDAQ:PEG",
    "PTC Inc. (US)": "NASDAQ:PTC",
    "Public Storage (US)": "NASDAQ:PSA",
    "PulteGroup (US)": "NASDAQ:PHM",
    "Quanta Services (US)": "NASDAQ:PWR",
    "Qualcomm (US)": "NASDAQ:QCOM",
    "Quest Diagnostics (US)": "NASDAQ:DGX",
    "Qnity Electronics (US)": "NASDAQ:Q",
    "Ralph Lauren Corporation (US)": "NASDAQ:RL",
    "Raymond James Financial (US)": "NASDAQ:RJF",
    "RTX Corporation (US)": "NASDAQ:RTX",
    "Realty Income (US)": "NASDAQ:O",
    "Regency Centers (US)": "NASDAQ:REG",
    "Regeneron Pharmaceuticals (US)": "NASDAQ:REGN",
    "Regions Financial Corporation (US)": "NASDAQ:RF",
    "Republic Services (US)": "NASDAQ:RSG",
    "ResMed (US)": "NASDAQ:RMD",
    "Revvity (US)": "NASDAQ:RVTY",
    "Robinhood Markets (US)": "NASDAQ:HOOD",
    "Rockwell Automation (US)": "NASDAQ:ROK",
    "Rollins, Inc. (US)": "NASDAQ:ROL",
    "Roper Technologies (US)": "NASDAQ:ROP",
    "Ross Stores (US)": "NASDAQ:ROST",
    "Royal Caribbean Group (US)": "NASDAQ:RCL",
    "S&P Global (US)": "NASDAQ:SPGI",
    "Salesforce (US)": "NASDAQ:CRM",
    "Sandisk (US)": "NASDAQ:SNDK",
    "SBA Communications (US)": "NASDAQ:SBAC",
    "Schlumberger (US)": "NASDAQ:SLB",
    "Seagate Technology (US)": "NASDAQ:STX",
    "Sempra (US)": "NASDAQ:SRE",
    "ServiceNow (US)": "NASDAQ:NOW",
    "Sherwin-Williams (US)": "NASDAQ:SHW",
    "Simon Property Group (US)": "NASDAQ:SPG",
    "Skyworks Solutions (US)": "NASDAQ:SWKS",
    "J.M. Smucker Company (The) (US)": "NASDAQ:SJM",
    "Smurfit Westrock (US)": "NASDAQ:SW",
    "Snap-on (US)": "NASDAQ:SNA",
    "Solventum (US)": "NASDAQ:SOLV",
    "Southern Company (US)": "NASDAQ:SO",
    "Southwest Airlines (US)": "NASDAQ:LUV",
    "Stanley Black & Decker (US)": "NASDAQ:SWK",
    "Starbucks (US)": "NASDAQ:SBUX",
    "State Street Corporation (US)": "NASDAQ:STT",
    "Steel Dynamics (US)": "NASDAQ:STLD",
    "Steris (US)": "NASDAQ:STE",
    "Stryker Corporation (US)": "NASDAQ:SYK",
    "Supermicro (US)": "NASDAQ:SMCI",
    "Synchrony Financial (US)": "NASDAQ:SYF",
    "Synopsys (US)": "NASDAQ:SNPS",
    "Sysco (US)": "NASDAQ:SYY",
    "T-Mobile US (US)": "NASDAQ:TMUS",
    "T. Rowe Price (US)": "NASDAQ:TROW",
    "Take-Two Interactive (US)": "NASDAQ:TTWO",
    "Tapestry, Inc. (US)": "NASDAQ:TPR",
    "Targa Resources (US)": "NASDAQ:TRGP",
    "Target Corporation (US)": "NASDAQ:TGT",
    "TE Connectivity (US)": "NASDAQ:TEL",
    "Teledyne Technologies (US)": "NASDAQ:TDY",
    "Teradyne (US)": "NASDAQ:TER",
    "Tesla, Inc. (US)": "NASDAQ:TSLA",
    "Texas Instruments (US)": "NASDAQ:TXN",
    "Texas Pacific Land Corporation (US)": "NASDAQ:TPL",
    "Textron (US)": "NASDAQ:TXT",
    "Thermo Fisher Scientific (US)": "NASDAQ:TMO",
    "TJX Companies (US)": "NASDAQ:TJX",
    "TKO Group Holdings (US)": "NASDAQ:TKO",
    "Trade Desk (The) (US)": "NASDAQ:TTD",
    "Tractor Supply (US)": "NASDAQ:TSCO",
    "Trane Technologies (US)": "NASDAQ:TT",
    "TransDigm Group (US)": "NASDAQ:TDG",
    "Travelers Companies (The) (US)": "NASDAQ:TRV",
    "Trimble Inc. (US)": "NASDAQ:TRMB",
    "Truist Financial (US)": "NASDAQ:TFC",
    "Tyler Technologies (US)": "NASDAQ:TYL",
    "Tyson Foods (US)": "NASDAQ:TSN",
    "U.S. Bancorp (US)": "NASDAQ:USB",
    "Uber (US)": "NASDAQ:UBER",
    "UDR, Inc. (US)": "NASDAQ:UDR",
    "Ulta Beauty (US)": "NASDAQ:ULTA",
    "Union Pacific Corporation (US)": "NASDAQ:UNP",
    "United Airlines Holdings (US)": "NASDAQ:UAL",
    "United Parcel Service (US)": "NASDAQ:UPS",
    "United Rentals (US)": "NASDAQ:URI",
    "UnitedHealth Group (US)": "NASDAQ:UNH",
    "Universal Health Services (US)": "NASDAQ:UHS",
    "Valero Energy (US)": "NASDAQ:VLO",
    "Ventas (US)": "NASDAQ:VTR",
    "Veralto (US)": "NASDAQ:VLTO",
    "Verisign (US)": "NASDAQ:VRSN",
    "Verisk Analytics (US)": "NASDAQ:VRSK",
    "Verizon (US)": "NASDAQ:VZ",
    "Vertex Pharmaceuticals (US)": "NASDAQ:VRTX",
    "Vertiv (US)": "NASDAQ:VRT",
    "Viatris (US)": "NASDAQ:VTRS",
    "Vici Properties (US)": "NASDAQ:VICI",
    "Visa Inc. (US)": "NASDAQ:V",
    "Vistra Corp. (US)": "NASDAQ:VST",
    "Vulcan Materials Company (US)": "NASDAQ:VMC",
    "W. R. Berkley Corporation (US)": "NASDAQ:WRB",
    "W. W. Grainger (US)": "NASDAQ:GWW",
    "Wabtec (US)": "NASDAQ:WAB",
    "Walmart (US)": "NASDAQ:WMT",
    "Walt Disney Company (The) (US)": "NASDAQ:DIS",
    "Warner Bros. Discovery (US)": "NASDAQ:WBD",
    "Waste Management (US)": "NASDAQ:WM",
    "Waters Corporation (US)": "NASDAQ:WAT",
    "WEC Energy Group (US)": "NASDAQ:WEC",
    "Wells Fargo (US)": "NASDAQ:WFC",
    "Welltower (US)": "NASDAQ:WELL",
    "West Pharmaceutical Services (US)": "NASDAQ:WST",
    "Western Digital (US)": "NASDAQ:WDC",
    "Weyerhaeuser (US)": "NASDAQ:WY",
    "Williams-Sonoma, Inc. (US)": "NASDAQ:WSM",
    "Williams Companies (US)": "NASDAQ:WMB",
    "Willis Towers Watson (US)": "NASDAQ:WTW",
    "Workday, Inc. (US)": "NASDAQ:WDAY",
    "Wynn Resorts (US)": "NASDAQ:WYNN",
    "Xcel Energy (US)": "NASDAQ:XEL",
    "Xylem Inc. (US)": "NASDAQ:XYL",
    "Yum! Brands (US)": "NASDAQ:YUM",
    "Zebra Technologies (US)": "NASDAQ:ZBRA",
    "Zimmer Biomet (US)": "NASDAQ:ZBH",
    "Zoetis (US)": "NASDAQ:ZTS",
    "Accor (FR)": "EPA:AC",
    "Air Liquide (FR)": "EPA:AI",
    "Airbus (FR)": "EPA:AIR",
    "ArcelorMittal (FR)": "EPA:MT.AS",
    "Axa (FR)": "EPA:CS",
    "BNP Paribas (FR)": "EPA:BNP",
    "Bouygues (FR)": "EPA:EN",
    "Bureau Veritas (FR)": "EPA:BVI",
    "Capgemini (FR)": "EPA:CAP",
    "Carrefour (FR)": "EPA:CA",
    "Crédit Agricole (FR)": "EPA:ACA",
    "Danone (FR)": "EPA:BN",
    "Dassault Systèmes (FR)": "EPA:DSY",
    "Edenred (FR)": "EPA:EDEN",
    "Engie (FR)": "EPA:ENGI",
    "EssilorLuxottica (FR)": "EPA:EL",
    "Eurofins Scientific (FR)": "EPA:ERF",
    "Hermès (FR)": "EPA:RMS",
    "Kering (FR)": "EPA:KER",
    "L'Oréal (FR)": "EPA:OR",
    "Legrand (FR)": "EPA:LR",
    "LVMH (FR)": "EPA:MC",
    "Michelin (FR)": "EPA:ML",
    "Orange (FR)": "EPA:ORA",
    "Pernod Ricard (FR)": "EPA:RI",
    "Publicis (FR)": "EPA:PUB",
    "Renault (FR)": "EPA:RNO",
    "Safran (FR)": "EPA:SAF",
    "Saint-Gobain (FR)": "EPA:SGO",
    "Sanofi (FR)": "EPA:SAN",
    "Schneider Electric (FR)": "EPA:SU",
    "Société Générale (FR)": "EPA:GLE",
    "Stellantis (FR)": "EPA:STLAP",
    "STMicroelectronics (FR)": "EPA:STMPA",
    "Teleperformance (FR)": "EPA:TEP",
    "Thales (FR)": "EPA:HO",
    "TotalEnergies (FR)": "EPA:TTE",
    "Unibail-Rodamco-Westfield (FR)": "EPA:URW",
    "Veolia (FR)": "EPA:VIE",
    "Vinci (FR)": "EPA:DG",
    "Adidas (DE)": "FRA:ADS",
    "Airbus (DE)": "FRA:AIR.PA",
    "Allianz (DE)": "FRA:ALV",
    "BASF (DE)": "FRA:BAS",
    "Bayer (DE)": "FRA:BAYN",
    "Beiersdorf (DE)": "FRA:BEI",
    "BMW (DE)": "FRA:BMW",
    "Brenntag (DE)": "FRA:BNR",
    "Commerzbank (DE)": "FRA:CBK",
    "Continental (DE)": "FRA:CON",
    "Daimler Truck (DE)": "FRA:DTG",
    "Deutsche Bank (DE)": "FRA:DBK",
    "Deutsche Börse (DE)": "FRA:DB1",
    "Deutsche Post (DE)": "FRA:DHL",
    "Deutsche Telekom (DE)": "FRA:DTE",
    "E.ON (DE)": "FRA:EOAN",
    "Fresenius (DE)": "FRA:FRE",
    "Fresenius Medical Care (DE)": "FRA:FME",
    "GEA Group (DE)": "FRA:G1A",
    "Hannover Re (DE)": "FRA:HNR1",
    "Heidelberg Materials (DE)": "FRA:HEI",
    "Henkel (DE)": "FRA:HEN3",
    "Infineon Technologies (DE)": "FRA:IFX",
    "Mercedes-Benz Group (DE)": "FRA:MBG",
    "Merck (DE)": "FRA:MRK",
    "MTU Aero Engines (DE)": "FRA:MTX",
    "Munich Re (DE)": "FRA:MUV2",
    "Porsche SE (DE)": "FRA:PAH3",
    "Qiagen (DE)": "FRA:QIA",
    "Rheinmetall (DE)": "FRA:RHM",
    "RWE (DE)": "FRA:RWE",
    "SAP (DE)": "FRA:SAP",
    "Scout24 (DE)": "FRA:G24",
    "Siemens (DE)": "FRA:SIE",
    "Siemens Energy (DE)": "FRA:ENR",
    "Siemens Healthineers (DE)": "FRA:SHL",
    "Symrise (DE)": "FRA:SY1",
    "Volkswagen Group (DE)": "FRA:VOW3",
    "Vonovia (DE)": "FRA:VNA",
    "Zalando (DE)": "FRA:ZAL"
}

PREDEFINED_PORTFOLIOS = {
    "Sélection Manuelle": [],
    "Portefeuille Warren Buffett": [
        "Apple Inc. (US)", "Bank of America (US)", "American Express (US)", 
        "Coca-Cola Company (The) (US)", "Chevron Corporation (US)", 
        "Occidental Petroleum (US)", "Kraft Heinz (US)"
    ],
    "Géants de la Tech (Magnificent 7)": [
        "Apple Inc. (US)", "Microsoft (US)", "Alphabet Inc. (Class A) (US)", 
        "Amazon (US)", "Nvidia (US)", "Meta Platforms (US)", "Tesla, Inc. (US)"
    ],
    "Tendances Positives US (S&P 500 Growth)": [
        "Nvidia (US)", "Broadcom (US)", "Lilly (Eli) (US)", 
        "Advanced Micro Devices (US)", "CrowdStrike (US)", "Palantir Technologies (US)"
    ],
    "Top Europe (Luxe & Tech)": [
        "LVMH (FR)", "L'Oréal (FR)", "SAP (DE)", 
        "Schneider Electric (FR)", "Siemens (DE)", "Hermès (FR)"
    ],
    "Tendances Asie / Chine (Tech & EVs)": [
        # Ajout direct de tickers Yahoo Finance pour la Chine car ils ne sont pas dans MAJOR_STOCKS
        "BABA", "TCEHY", "BYDDY", "BIDU", "JD"
    ]
}
